#!/usr/bin/env bash

set -eo pipefail

POD_LEIN_PROFILES="+uberjar"
POD_NAME="pod-babashka-$POD_DB_TYPE"
POD_REFLECTION_CONFIG="reflection-$POD_DB_TYPE.json"

if [ "$POD_DB_TYPE" = "postgresql" ]
then
    POD_LEIN_PROFILES+=",+feature/postgresql"
else
    POD_LEIN_PROFILES+=",-feature/postgresql"
fi

if [ "$POD_DB_TYPE" = "hsqldb" ]
then
    POD_LEIN_PROFILES+=",+feature/hsqldb"
else
    POD_LEIN_PROFILES+=",-feature/hsqldb"
fi

if [ "$POD_DB_TYPE" = "mysql" ]
then
    POD_LEIN_PROFILES+=",+feature/mysql"
else
    POD_LEIN_PROFILES+=",-feature/mysql"
fi

if [ "$POD_DB_TYPE" = "oracle" ]
then
    POD_LEIN_PROFILES+=",+feature/oracle"
else
    POD_LEIN_PROFILES+=",-feature/oracle"
fi

if [ "$POD_DB_TYPE" = "mssql" ]
then
    POD_LEIN_PROFILES+=",+feature/mssql"
else
    POD_LEIN_PROFILES+=",-feature/mssql"
fi

VERSION=$(cat resources/POD_BABASHKA_SQL_VERSION)

JAR="target/pod-babashka-sql-$VERSION-standalone.jar"

echo "$POD_LEIN_PROFILES"
echo "$POD_REFLECTION_CONFIG"

java -version
lein with-profiles "$POD_LEIN_PROFILES" "do" clean, uberjar


BABASHKA_XMX=${BABASHKA_XMX:-"-J-Xmx4500m"}

args=( "-jar" "$JAR"
       "-H:Name=$POD_NAME"
       "-H:+ReportExceptionStackTraces"
       "-J-Dclojure.spec.skip-macros=true"
       "-J-Dclojure.compiler.direct-linking=true"
       "-H:IncludeResources=POD_BABASHKA_SQL_VERSION"
       "-H:ReflectionConfigurationFiles=$POD_REFLECTION_CONFIG"
       "--initialize-at-build-time"
       "-H:Log=registerResource:"
       "-H:EnableURLProtocols=http,https"
       "--enable-all-security-services"
       "--allow-incomplete-classpath"
       "-H:+JNI"
       "--verbose"
       "--no-fallback"
       "--no-server"
       "--report-unsupported-elements-at-runtime"
       "-H:+AddAllCharsets"
       "-H:IncludeResources=org/hsqldb/.*\.properties"
       "-H:IncludeResources=org/hsqldb/.*\.sql"
       "-H:IncludeResources=mariadb.properties"
       "--initialize-at-run-time=org.mariadb.jdbc.Driver"
       "--initialize-at-run-time=org.mariadb.jdbc.client.socket.impl.UnixDomainSocket"
       "--initialize-at-run-time=org.mariadb.jdbc.client.socket.impl.UnixDomainSocket$SockAddr"
       "--initialize-at-run-time=org.postgresql.sspi.SSPIClient"
       "--initialize-at-run-time=com.microsoft.sqlserver.jdbc.SQLServerColumnEncryptionAzureKeyVaultProvider"
       "--initialize-at-run-time=com.microsoft.sqlserver.jdbc.SQLServerFMTQuery"
       "--initialize-at-run-time=com.microsoft.sqlserver.jdbc.SQLServerBouncyCastleLoader"
       "--initialize-at-run-time=com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils"
       "$BABASHKA_XMX" )

if [ "$POD_DB_TYPE" = "mssql" ]
then
    args+=("-H:IncludeResourceBundles=com.microsoft.sqlserver.jdbc.SQLServerResource")
fi

if [ "$BABASHKA_STATIC" = "true" ]; then
    args+=("--static")
    if [ "$BABASHKA_MUSL" = "true" ]; then
        args+=("--libc=musl"
               # see https://github.com/oracle/graal/issues/3398
               "-H:CCompilerOption=-Wl,-z,stack-size=2097152")
    fi
fi

native-image "${args[@]}"
